#!/usr/bin/env python3
"""Generate the PGFPlots rolling-stability range figure for M4.2."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from generate_lead_lag_figure import LABELS, RELATIONSHIP_ORDER


PUBLICATION_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = Path(__file__).resolve().parents[3]
REPORT_PATH = PROJECT_ROOT / "reports/cycle_analysis/cf_lead_lag_stability_v1.json"
OUTPUT_PATH = PUBLICATION_ROOT / "figures/cf_lead_lag_rolling_stability.tex"

DECISION_STYLE = {
    "ACCEPT_BRIDGE": ("cfBridge", "*", "经营桥"),
    "ACCEPT_CORE_VALIDATION": ("cfCore", "square*", "核心验证"),
    "ACCEPT_CONFIRMATION": ("cfConfirmation", "triangle*", "市场确认"),
    "ACCEPT_DEMAND": ("cfDemand", "pentagon*", "需求输入"),
    "CONDITIONAL": ("cfConditional", "diamond*", "条件使用"),
    "REJECT": ("cfReject", "x", "拒绝"),
    "DIAGNOSTIC": ("cfDiagnostic", "square*", "诊断"),
}


def main() -> int:
    report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    by_id = {row["relationship_id"]: row for row in report["decisions"]}
    missing = set(RELATIONSHIP_ORDER) - set(by_id)
    if missing:
        raise ValueError(f"Stability report is missing relationships: {sorted(missing)}")
    rows = [by_id[relationship_id] for relationship_id in RELATIONSHIP_ORDER]
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(_render(rows, report), encoding="utf-8")
    print(f"stability_figure_rows={len(rows)} output={OUTPUT_PATH}")
    return 0


def _render(rows: list[dict], report: dict) -> str:
    total = len(rows)
    labels_by_y: dict[int, str] = {}
    medians: dict[str, list[str]] = defaultdict(list)
    full_sample: list[str] = []
    ranges: list[str] = []
    for index, row in enumerate(rows):
        y_value = total - index
        relationship_id = row["relationship_id"]
        decision = row["decision"]
        color = DECISION_STYLE[decision][0]
        minimum = float(row["rolling_min_correlation"])
        maximum = float(row["rolling_max_correlation"])
        median = float(row["rolling_median_correlation"])
        full = float(row["full_sample_correlation"])
        labels_by_y[y_value] = LABELS[relationship_id]
        ranges.extend(
            [
                f"\\addplot[{color},line width=1.0pt,forget plot] coordinates {{",
                f"  ({minimum:.6f},{y_value}) ({maximum:.6f},{y_value})",
                "};",
            ]
        )
        medians[decision].append(f"  ({median:.6f},{y_value})")
        full_sample.append(f"  ({full:.6f},{y_value})")

    lines = [
        "% Generated by scripts/generate_stability_figure.py; do not edit manually.",
        f"% Source analysis: {report['analysis_id']} v{report['version']}",
        "\\definecolor{cfBridge}{HTML}{0072B2}",
        "\\definecolor{cfCore}{HTML}{005A8D}",
        "\\definecolor{cfConfirmation}{HTML}{009E73}",
        "\\definecolor{cfDemand}{HTML}{56B4E9}",
        "\\definecolor{cfConditional}{HTML}{E69F00}",
        "\\definecolor{cfReject}{HTML}{D55E00}",
        "\\definecolor{cfDiagnostic}{HTML}{7B3294}",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  width=0.63\\textwidth,",
        "  height=15.2cm,",
        "  xmin=-0.80, xmax=1.08,",
        "  ymin=0.35, ymax=14.85,",
        "  axis x line*=bottom,",
        "  axis y line*=left,",
        "  y axis line style={draw=none},",
        "  ytick style={draw=none},",
        "  xlabel={固定滞后下的相关系数},",
        "  xtick={-0.75,-0.50,-0.25,0,0.25,0.50,0.75,1.00},",
        "  grid=both,",
        "  major grid style={black!12},",
        "  minor grid style={black!5},",
        "  ytick={" + ",".join(str(value) for value in range(1, total + 1)) + "},",
        "  yticklabels={"
        + ",".join("{" + labels_by_y[value] + "}" for value in range(1, total + 1))
        + "},",
        "  yticklabel style={font=\\scriptsize,align=right,text width=6.0cm},",
        "  tick label style={font=\\scriptsize},",
        "  label style={font=\\small},",
        "  legend style={at={(0.5,-0.10)},anchor=north,draw=none,font=\\scriptsize,/tikz/every even column/.append style={column sep=0.16cm}},",
        "  legend columns=3,",
        "]",
        "\\addplot[black!55,thin,forget plot] coordinates {(0,0.5) (0,14.65)};",
        "\\addplot[black!25,dashed,forget plot] coordinates {(-0.80,5.5) (1.08,5.5)};",
        "\\node[anchor=west,font=\\scriptsize\\bfseries,text=black!70] at (axis cs:-0.78,14.55) {经济期经营传导};",
        "\\node[anchor=west,font=\\scriptsize\\bfseries,text=black!70] at (axis cs:-0.78,5.35) {可用期与市场反应};",
        *ranges,
    ]
    for decision in DECISION_STYLE:
        coordinates = medians.get(decision)
        if not coordinates:
            continue
        color, marker, legend = DECISION_STYLE[decision]
        lines.extend(
            [
                f"\\addplot[only marks,color={color},mark={marker},mark size=2.5pt] coordinates {{",
                *coordinates,
                "};",
                f"\\addlegendentry{{滚动中位：{legend}}}",
            ]
        )
    lines.extend(
        [
            "\\addplot[only marks,color=black,mark=diamond,mark size=2.8pt,mark options={fill=white}] coordinates {",
            *full_sample,
            "};",
            "\\addlegendentry{全样本相关}",
            "\\end{axis}",
            "\\end{tikzpicture}",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
