#!/usr/bin/env python3
"""Generate the PGFPlots fragment for the M4.1 best-lag coefficient figure."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path


PUBLICATION_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = Path(__file__).resolve().parents[3]
REPORT_PATH = PROJECT_ROOT / "reports/cycle_analysis/cf_lead_lag_v1.json"
OUTPUT_PATH = PUBLICATION_ROOT / "figures/cf_lead_lag_best_coefficients.tex"

RELATIONSHIP_ORDER = [
    "quarterly_urea_to_granular_urea_price_change",
    "quarterly_urea_to_ammonia_price_change",
    "quarterly_urea_to_uan_price_change",
    "quarterly_urea_to_ammonium_nitrate_price_change",
    "quarterly_henry_hub_to_cf_gas_cost_change",
    "quarterly_global_spread_to_cf_realized_spread_change",
    "quarterly_global_spread_to_gross_margin_change",
    "quarterly_global_spread_to_ebitda_change",
    "quarterly_corn_to_cf_volume_yoy_change",
    "monthly_disclosed_margin_change_to_cf_return",
    "monthly_disclosed_realized_spread_change_to_cf_return",
    "monthly_global_spread_change_to_cf_return",
    "monthly_corn_change_to_cf_return",
    "monthly_henry_hub_change_to_global_spread_change",
]

LABELS = {
    "quarterly_urea_to_granular_urea_price_change": "全球尿素 $\\rightarrow$ 颗粒尿素实现价（同期）",
    "quarterly_urea_to_ammonia_price_change": "全球尿素 $\\rightarrow$ 氨实现价（1 季）",
    "quarterly_urea_to_uan_price_change": "全球尿素 $\\rightarrow$ UAN 实现价（1 季）",
    "quarterly_urea_to_ammonium_nitrate_price_change": "全球尿素 $\\rightarrow$ 硝酸铵实现价（1 季）",
    "quarterly_henry_hub_to_cf_gas_cost_change": "Henry Hub $\\rightarrow$ CF 实际气价（1 季）",
    "quarterly_global_spread_to_cf_realized_spread_change": "全球气价差 $\\rightarrow$ CF 实现气价差（同期）",
    "quarterly_global_spread_to_gross_margin_change": "全球气价差 $\\rightarrow$ CF 毛利率变化（同期）",
    "quarterly_global_spread_to_ebitda_change": "全球气价差 $\\rightarrow$ CF EBITDA 变化（同期）",
    "quarterly_corn_to_cf_volume_yoy_change": "玉米 $\\rightarrow$ CF 销量同比（1 季）",
    "monthly_disclosed_margin_change_to_cf_return": "已披露毛利变化 $\\rightarrow$ CF 单月收益（5 月）",
    "monthly_disclosed_realized_spread_change_to_cf_return": "已披露实现气价差 $\\rightarrow$ CF 单月收益（5 月）",
    "monthly_global_spread_change_to_cf_return": "全球气价差 $\\rightarrow$ CF 单月收益（8 月）",
    "monthly_corn_change_to_cf_return": "玉米 $\\rightarrow$ CF 单月收益（12 月）",
    "monthly_henry_hub_change_to_global_spread_change": "Henry Hub $\\rightarrow$ 全球气价差（同期）",
}

STATUS_STYLE = {
    "STRONG": ("cfStrong", "*", "STRONG"),
    "DIRECTIONAL": ("cfDirectional", "triangle*", "DIRECTIONAL"),
    "CONTRADICTORY": ("cfContradictory", "diamond*", "CONTRADICTORY"),
    "UNSTABLE": ("cfUnstable", "*", "UNSTABLE"),
    "INSUFFICIENT": ("cfInsufficient", "square*", "INSUFFICIENT"),
    "DIAGNOSTIC": ("cfDiagnostic", "square*", "DIAGNOSTIC"),
}


def main() -> int:
    report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    by_id = {row["relationship_id"]: row for row in report["best_lags"]}
    missing = set(RELATIONSHIP_ORDER) - set(by_id)
    if missing:
        raise ValueError(f"Report is missing configured relationships: {sorted(missing)}")
    rows = [by_id[relationship_id] for relationship_id in RELATIONSHIP_ORDER]
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(_render(rows, report), encoding="utf-8")
    print(f"figure_rows={len(rows)} output={OUTPUT_PATH}")
    return 0


def _render(rows: list[dict], report: dict) -> str:
    total = len(rows)
    plotted: dict[str, list[str]] = defaultdict(list)
    labels_by_y: dict[int, str] = {}
    for index, row in enumerate(rows):
        y_value = total - index
        estimate = float(row["correlation"])
        half_width = 1.96 * float(row["hac_standard_error"])
        status = row["evidence_status"]
        labels_by_y[y_value] = LABELS[row["relationship_id"]]
        plotted[status].append(
            f"    ({estimate:.6f},{y_value}) +- ({half_width:.6f},0)"
        )

    lines = [
        "% Generated by scripts/generate_lead_lag_figure.py; do not edit manually.",
        f"% Source analysis: {report['analysis_id']} v{report['version']}",
        "\\definecolor{cfStrong}{HTML}{0072B2}",
        "\\definecolor{cfDirectional}{HTML}{009E73}",
        "\\definecolor{cfContradictory}{HTML}{D55E00}",
        "\\definecolor{cfUnstable}{HTML}{999999}",
        "\\definecolor{cfInsufficient}{HTML}{CCCCCC}",
        "\\definecolor{cfDiagnostic}{HTML}{7B3294}",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  width=0.63\\textwidth,",
        "  height=15.2cm,",
        "  xmin=-0.80, xmax=1.08,",
        "  ymin=0.35, ymax=14.85,",
        "  axis x line*=bottom,",
        "  axis y line*=left,",
        "  y axis line style={draw=none},",
        "  ytick style={draw=none},",
        "  xlabel={最佳滞后的相关系数 / 标准化回归斜率},",
        "  xtick={-0.75,-0.50,-0.25,0,0.25,0.50,0.75,1.00},",
        "  grid=both,",
        "  major grid style={black!12},",
        "  minor grid style={black!5},",
        "  ytick={" + ",".join(str(value) for value in range(1, total + 1)) + "},",
        "  yticklabels={"
        + ",".join("{" + labels_by_y[value] + "}" for value in range(1, total + 1))
        + "},",
        "  yticklabel style={font=\\scriptsize,align=right,text width=6.0cm},",
        "  tick label style={font=\\scriptsize},",
        "  label style={font=\\small},",
        "  legend style={at={(0.5,-0.10)},anchor=north,draw=none,font=\\scriptsize,/tikz/every even column/.append style={column sep=0.18cm}},",
        "  legend columns=4,",
        "]",
        "\\addplot[black!55,thin,forget plot] coordinates {(0,0.5) (0,14.65)};",
        "\\addplot[black!25,dashed,forget plot] coordinates {(-0.80,5.5) (1.08,5.5)};",
        "\\node[anchor=west,font=\\scriptsize\\bfseries,text=black!70] at (axis cs:-0.78,14.55) {经济期经营传导};",
        "\\node[anchor=west,font=\\scriptsize\\bfseries,text=black!70] at (axis cs:-0.78,5.35) {可用期与市场反应};",
    ]
    for status in STATUS_STYLE:
        coordinates = plotted.get(status)
        if not coordinates:
            continue
        color, marker, legend = STATUS_STYLE[status]
        lines.extend(
            [
                "\\addplot+[",
                "  only marks,",
                f"  color={color}, mark={marker}, mark size=2.4pt,",
                "  error bars/.cd, x dir=both, x explicit,",
                "  error bar style={line width=0.7pt},",
                "  error mark options={rotate=90,mark size=2pt,line width=0.7pt},",
                "] coordinates {",
                *coordinates,
                "};",
                f"\\addlegendentry{{{legend}}}",
            ]
        )
    lines.extend(["\\end{axis}", "\\end{tikzpicture}", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
